apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
  labels:
    app: sg-develop
    redis-client: "true"
  name: sg-develop
  namespace: develop
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sg-develop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sg-develop
        redis-client: "true"
    spec:
      containers:
      - args:
        - python manage.py migrate; gunicorn website.asgi:application -k uvicorn.workers.UvicornWorker
        command:
        - /bin/sh
        - -c
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: mongod-name
              name: sg-secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongod-url
              name: sg-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongod-pass
              name: sg-secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongod-user
              name: sg-secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: sg-secret
        - name: SMTP_EMAIL
          valueFrom:
            secretKeyRef:
              key: smtp-email
              name: sg-secret
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: smtp-pass
              name: sg-secret
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: env
              name: sg-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-host
              name: sg-secret
        image: <image-name>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: sg-develop
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/website/media
          name: media
      - args:
        - celery -A website worker -l info;
        command:
        - /bin/sh
        - -c
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: mongod-name
              name: sg-secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongod-url
              name: sg-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongod-pass
              name: sg-secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongod-user
              name: sg-secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: sg-secret
        - name: SMTP_EMAIL
          valueFrom:
            secretKeyRef:
              key: smtp-email
              name: sg-secret
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: smtp-pass
              name: sg-secret
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: env
              name: sg-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-host
              name: sg-secret
        image: <image-name>
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: celery
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/website/media
          name: media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: media