apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "143"
  creationTimestamp: "2020-02-18T11:10:54Z"
  generation: 143
  labels:
    app: sg-develop
    redis-client: "true"
  name: sg-develop
  namespace: develop
  resourceVersion: "18541469"
  selfLink: /apis/extensions/v1beta1/namespaces/develop/deployments/sg-develop
  uid: 1c41a7dc-31b2-4026-ba3b-e65c91f96ea4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sg-develop
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sg-develop
        redis-client: "true"
    spec:
      containers:
      - args:
        - python manage.py migrate; gunicorn website.asgi:application -k uvicorn.workers.UvicornWorker
        command:
        - /bin/sh
        - -c
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: mongod-name
              name: sg-secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongod-url
              name: sg-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongod-pass
              name: sg-secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongod-user
              name: sg-secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: sg-secret
        - name: SMTP_EMAIL
          valueFrom:
            secretKeyRef:
              key: smtp-email
              name: sg-secret
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: smtp-pass
              name: sg-secret
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: env
              name: sg-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-host
              name: sg-secret
        image: eu.gcr.io/calcium-range-262011/sgeip-develop:99
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: sg-develop
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 1500m
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 3Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/website/media
          name: media
      - args:
        - celery -A website worker -l info;
        command:
        - /bin/sh
        - -c
        env:
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              key: mongod-name
              name: sg-secret
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              key: mongod-url
              name: sg-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mongod-pass
              name: sg-secret
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: mongod-user
              name: sg-secret
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secretKey
              name: sg-secret
        - name: SMTP_EMAIL
          valueFrom:
            secretKeyRef:
              key: smtp-email
              name: sg-secret
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: smtp-pass
              name: sg-secret
        - name: ENVIRONMENT
          valueFrom:
            secretKeyRef:
              key: env
              name: sg-secret
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-host
              name: sg-secret
        image: eu.gcr.io/calcium-range-262011/sgeip-develop:99
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: celery
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health/
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 400m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/website/media
          name: media
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: media
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-02-18T11:10:55Z"
    lastUpdateTime: "2020-02-18T11:10:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-03-16T09:08:20Z"
    lastUpdateTime: "2020-03-20T10:37:06Z"
    message: ReplicaSet "sg-develop-79944cf66b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 143
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
