kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rolebinding-name
  namespace: develop
subjects:
- kind: User
#the same email addr for the user that are already part of IAM service...
  name: email_addr
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: <role-name>
  apiGroup: rbac.authorization.k8s.io