#You have to install rbac-manager (from helm/stable repo) before you are able to use this kind of Kubernetes objects
apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: edit-access-for-developers
rbacBindings:
  - name: developers
    subjects:
      - kind: User
      #the same email addr for that user that are already part of IAM service...
        name: valid-email-address 
      - kind: User
        name: valid-email-address 
    roleBindings:
      - namespace: develop
      #you will have to create your clusteRole first, if you want everything to works as expected
        clusterRole: developers-cr 
      - namespace: staging
        clusterRole: developers-cr
      - namespace: production
        clusterRole: developers-cr